export default class Constants {



  /**
   * title font weight
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * aspect ratio
   */
  static readonly BANNER_ASPECT_RATIO: number = 1.5;

  /**
   * animate duration
   */
  static readonly BANNER_ANIMATE_DURATION: number = 300;

  /**
   * share delay
   */
  static readonly SHARE_TRANSITION_DELAY: number = 100;

  /**
   * aspect ratio
   */
  static readonly STACK_IMG_RATIO: number = 0.7;

  /**
   * item space
   */
  static readonly LIST_ITEM_SPACE: number = 2;



  /**
   *  percent
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * photo item percent
   */
  static readonly PHOTO_ITEM_PERCENT: string = '90%';

  /**
   * show count
   */
  static readonly SHOW_COUNT: number = 8;

  /**
   * default width
   */
  static readonly DEFAULT_WIDTH: number = 360;

  /**
   * padding
   */
  static readonly PHOTO_ITEM_PADDING: number = 8;

  /**
   * offset
   */
  static readonly PHOTO_ITEM_OFFSET: number = 16;

  /**
   * item opacity offset
   */
  static readonly ITEM_OPACITY_OFFSET: number = 0.2;

}
